locale = "ru"
label = "Русский"
weight = 3

title = "Zürafa Architecture"
description = "Портфолио архитектора Хакана Карамана — жилые, коммерческие, культурные проекты и реставрация в Турции"

[params]
  isoCode = "ru"
  displayName = "🇷🇺"
  description = "Портфолио архитектора Хакана Карамана — жилые, коммерческие, культурные проекты и реставрация в Турции"

[params.author]
  name = "Zürafa"
  image = "img/logo.png"
  email = "karaman.hakan@gmail.com"
  headline = "Архитектурное агентство Хакана Карамана"
  bio = "Наше архитектурное агентство предоставляет полный спектр архитектурных услуг."
   links = [
     { email = "mailto:karaman.hakan@gmail.com" },
     { facebook = "https://facebook.com/profile.php?id=100037610876403" },
     { instagram = "https://instagram.com/hakankaramanmimarlik" },
     { pinterest = "https://pinterest.com/karamanhakan" },
     { telegram = "https://t.me/hakankaramanmimarlik" },
     { whatsapp = "https://wa.me/905395690900" },
   ]
