# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "Hizmetlerimiz"
 pageRef = "services"
 weight = 10

[[main]]
 name = "Mimari Tasarım"
 parent = "Hizmetlerimiz"
 pageRef = "services/architecture"
 weight = 10

[[main]]
 name = "İç Mekan Tasarımı"
 parent = "Hizmetlerimiz"
 pageRef = "services/interior"
 weight = 20

[[main]]
 name = "Peyzaj Tasarımı"
 parent = "Hizmetlerimiz"
 pageRef = "services/landscape"
 weight = 30

[[main]]
 name = "Restorasyon ve Yenileme"
 parent = "Hizmetlerimiz"
 pageRef = "services/restoration"
 weight = 40

[[main]]
  name = "Projeler"
  pageRef = "project"
  weight = 20

[[main]]
  name = "Tamamlanan Projeler"
  parent = "Projeler"
  pageRef = "project/completed"
  weight = 21

[[main]]
  name = "Konut Projeleri"
  parent = "Projeler"
  pageRef = "project/residental"
  weight = 22

[[main]]
  name = "Ticari Projeler"
  parent = "Projeler"
  pageRef = "project/commercial"
  weight = 23

[[main]]
  name = "Kamu Binaları"
  parent = "Projeler"
  pageRef = "project/public"
  weight = 24

[[main]]
  name = "Kültürel ve Tarihi Miras Projeleri"
  parent = "Projeler"
  pageRef = "project/cultural"
  weight = 25

[[main]]
  name = "Referanslar"
  pageRef = "reference"
  weight = 30

[[main]]
  name = "Hakkımızda"
  pageRef = "about"
  weight = 100

#[[main]]
#  name = "Merch"
#  url = "http://tee.pub/lic/qwSlWVBL5zc"
#  weight = 100

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

# [[main]]
#   identifier = "twitter"
#   pre = "twitter"
#   url = "https://twitter.com/burufugu"
#   weight = 200

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10
