# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "Services"
 pageRef = "services"
 weight = 10

[[main]]
 name = "Architectural Design"
 parent = "Services"
 pageRef = "services/architecture"
 weight = 10

[[main]]
 name = "Interior Design"
 parent = "Services"
 pageRef = "services/interior"
 weight = 20

[[main]]
 name = "Landscape Design"
 parent = "Services"
 pageRef = "services/landscape"
 weight = 30

[[main]]
 name = "Restoration and Renovation"
 parent = "Services"
 pageRef = "services/restoration"
 weight = 40

[[main]]
  name = "Projects"
  pageRef = "project"
  weight = 20

[[main]]
  name = "Completed Projects"
  parent = "Projects"
  pageRef = "project/completed"
  weight = 21

[[main]]
  name = "Residential Projects"
  parent = "Projects"
  pageRef = "project/residental"
  weight = 22

[[main]]
  name = "Commercial Projects"
  parent = "Projects"
  pageRef = "project/commercial"
  weight = 23

[[main]]
  name = "Public Buildings"
  parent = "Projects"
  pageRef = "project/public"
  weight = 24

[[main]]
  name = "Cultural and Heritage Projects"
  parent = "Projects"
  pageRef = "project/cultural"
  weight = 25

[[main]]
  name = "References"
  pageRef = "reference"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 100

#[[main]]
#  name = "Merch"
#  url = "http://tee.pub/lic/qwSlWVBL5zc"
#  weight = 100

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/burufugu"
  weight = 200

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10
