# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters
colorScheme = "slate"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

[font]
  [font.heading]
    family = "DM Serif Display"
    [[font.heading.sizes]]
      size = "3xl"
      weight = "normal"
      lineHeight = "1.2"
  [font.body]
    family = "Inter"
    [[font.body.sizes]]
      size = "base"
      weight = "300"
      lineHeight = "1.7"
rtl = false
dateFormat = "2 January 2006"

copyright = "Copyright © 2023-{ year } Hakan Karaman; Created by [AleLab](https://github.com/a1e-lab/)"

enableSearch = true
enableCodeCopy = false
enableImageLazyLoading = true

# robots = ""
fingerprintAlgorithm = "sha256"

mainSections = ["project"]

disableImageOptimization = false

# logo = "img/logo.png"
# secondaryLogo = "img/light_logo.png"

defaultBackgroundImage = "img/bg.jpg"
defaultFeaturedImage = "img/bg.jpg"

highlightCurrentMenuArea = true
smartTOC = false
smartTOCHideUnfocusedChildren = false

[author]
  name = "Zürafa"
  image = "img/logo.png"
  email = "karaman.hakan@gmail.com"
  headline = "Hakan Karaman Mimarlık Ajansı | Architecture Agency"
  bio = "Mimarlık ajansımız çok çeşitli mimari hizmetler sunmaktadır."
  links = [
    { email = "mailto:karaman.hakan@gmail.com" },
    { facebook = "https://facebook.com/profile.php?id=100037610876403" },
    { instagram = "https://instagram.com/hakankaramanmimarlik" },
    { pinterest = "https://pinterest.com/karamanhakan" },
    { telegram = "https://t.me/hakankaramanmimarlik" },
    { whatsapp = "https://wa.me/905395690900" },
  ]

[header]
  layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-fill-blur
  # logoDark = "img/dark-location.jpg"
  showTitle = false

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
  showMenu = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/bg.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/project"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = false
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true 
  showAuthorsBadges = true 
  showWordCount = false
  showSummary = true
  sharingLinks = [ "whatsapp", "telegram", "pinterest", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

# mainSections = ["section1", "section2"]
# robots = ""
